### ISSUE TITLE
Data cleanup/archiving

### ISSUE THREAD

**Issue by kristofdepypere** [structurizr/onpremises#10]
Hi,

For now we are using local storage for structurizr on premise and we are starting to get out of disk space errors.

We are uploading very often new versions of structurizr workspaces in our automated pipelines. Often even without changes. So a few questions on what are operationally our options:

- It appears the structurizr workspace versions are all kept, even though there are no changes. Is there any way to optimize this ?
- What are the ways we can archive/delete old versions of our workspaces ? Can we disable versioning or at least limit to a maximum amount of workspaces ? Do we create our own cleanup process to remove?

**Comment by simonbrowndotje** [comment]
There's a scheduled job built in to the on-premises installation that removes all workspace versions older than 365 days. But this can be changed, and perhaps doing something like keeping the most recent X versions (where X is configurable) would be better. Would that work for you?

**Comment by kristofdepypere** [comment]
That would work. making the this '365 days' setting configurable would solve our issues

**Comment by simonbrowndotje** [comment]
This will be available in build 2905+ (later today) ... a property named `structurizr.maxWorkspaceVersions` can be used to customise the number of workspace versions stored (default=30).
