### ISSUE TITLE
Kubernetes config

### ISSUE THREAD

**Issue by pixeldrew** [structurizr/onpremises#12]
I'm trying to deploy structurizr to a kubernetes cluster and trying to write a config map that uses env vars loaded from Secrets. This is to protect the passwords for Elastic Search and Redis.

The apache commons configuration should support env vars interpolated in the structurizr.properties file but it's not working, for example:

structurizr.url=${env:URL}

Can you suggest a work around?

**Comment by pixeldrew** [comment]
For example: https://commons.apache.org/proper/commons-configuration/userguide/howto_basicfeatures.html

**Comment by simonbrowndotje** [comment]
I just went to add this as a feature, and it looks it's already supported via some underlying magic in Spring, and you can just specify the environment variables via the `${...}` syntax. For example:

```
structurizr.session=redis
structurizr.redis.host=${REDIS_HOST}
structurizr.redis.port=${REDIS_PORT}
structurizr.redis.password=${REDIS_PASSWORD}
```

**Comment by pixeldrew** [comment]
I'm thinking ${env:NAME} doesn't work, but ${NAME} does, maybe it's an apache commons version difference

**Comment by simonbrowndotje** [comment]
Structurizr isn't using Apache Commons Configuration.

**Comment by pixeldrew** [comment]
you're using spring to parse the config? Great if Spring does it then. Thanks, I guess we can close this ticket, maybe just some documentation would help

**Comment by simonbrowndotje** [comment]
Let's leave this issue open - I'd like to add the same support for the some of the properties where this doesn't work (e.g. `structurizr.url`. Once done, I'll add it to the docs.
