### ISSUE TITLE
Generate a new dev image on dockerhub

### ISSUE THREAD

**Issue by paulohumberto42** [structurizr/onpremises#134]
### Description

Recently, I pushed a bug fix related to the integration with Azure Blob Storage. It is already in the main branch but has not been published in the dev image on DockerHub. Would it be possible to publish it?"

### Priority

I have no budget and there's no rush, please add this feature for free

**Comment by simonbrowndotje** [comment]
`structurizr/onpremises:dev` has now been updated.
