### ISSUE TITLE
Issue with cookie domain name using SAML login and custom domain.

### ISSUE THREAD

**Issue by thecodetinker** [structurizr/onpremises#14]
Hi - I'm having a bit of trouble setting up Structurizr On-Prem behind a custom domain using an Azure Front Door reverse proxy. Structurizr itself is hosted on an appservice like 

https://mystructurizrinstance.azurewebsites.net/

But the site is accessed via the Front Door at

https://structurizr.mydomain.com/

I've set the properties as so:

```
structurizr.authentication=saml
structurizr.url=https://structurizr.mydomain.com
structurizr.replyurl=https://structurizr.mydomain.com/saml/SSO
structurizr.saml.entityId=structurizr
```

And the site works, images load etc. But when I try to log in, the cookie is blocked because the domain name is still set to the `azurewebsites.net` rather than `mydomain.com`. 

Therefore I just get 

![image](https://user-images.githubusercontent.com/14968003/215052550-630f0210-219c-4a3e-a5a1-277e6afd3038.png)

With dev tools showing:

![image](https://user-images.githubusercontent.com/14968003/215052135-b51f86bb-0125-47be-8355-9bbc6c2b78bb.png)

I'm not sure how I can configure the domain of the SAML cookie, should it not come from the domain of the `structurizr.url`? Any help would be much appreciated!

**Comment by simonbrowndotje** [comment]
I don't know much about Azure I'm afraid, so you might want to [join the Slack group](https://join.slack.com/t/structurizr/shared_invite/enQtMzkyMjY1NzMwNTkzLTcyOGI1MTZmNDQwMDQ5YmZlMThiYmU1ZTM2ZWZiMzYwMjVhNmM0OWIwNjFlZTM1YmY3YzU0ZDY2MTA1YTk5Mjg) and ask on there. There may be some tips in #8 too.

**Comment by thecodetinker** [comment]
Ok, thanks for the quick answer. I wasn't sure what was setting this Domain, whether it's Azure or Spring.

**Comment by simonbrowndotje** [comment]
`ARRAffinitySameSite` looks like an Azure specific cookie related to session management, so I don't think it's a Spring cookie.

**Comment by thecodetinker** [comment]
Hmm maybe that's not the reason for the 403 - thanks for confirming. I'll keep looking!
