### ISSUE TITLE
Add support for configuring Redis connection to use TLS

### ISSUE THREAD

**Issue by pmoncznik** [structurizr/onpremises#144]
### Description

I'd like to add a new `structurizr.redis.tls` configuration property that when set to `true` would configure the Redis connection for caching and/or session storage to use TLS/SSL.

### Priority

I'm willing to add this feature myself and raise a PR (please confirm approach first)

**Comment by simonbrowndotje** [comment]
I've added support for Redis SSL/TLS connections while refactoring how configuration is handled. You can enable secure connections using one of the following approaches:

## Option 1. Setting the protocol

- `structurizr.redis.protocol=rediss`

## Option 2. Setting the full endpoint

- `structurizr.redis.endpoint=rediss://example.com:1234`
