### ISSUE TITLE
Add entry on dashboard for “Review links management”

### ISSUE THREAD

**Issue by cavies** [structurizr/onpremises#16]
I wonder if you can provide a management entry about Review on the Dashboard to view the list of Review links I created. Now I need to manually save the token, which may lead to forgetting. It would be best if you could provide the deletion of the review link.

**Comment by simonbrowndotje** [comment]
As a part of the work to open source the codebase, I'm contemplating splitting out the review functionality from the on-premises installation entirely, and creating another standalone app. Either way, I'll be sure to include a way to manage reviews.

**Comment by simonbrowndotje** [comment]
Fixed by https://github.com/structurizr/onpremises/commit/85cb89379cabeac0d6276e2fa540cd7ae4faadf4
