### ISSUE TITLE
Problem loading diagrams when using build 2983

### ISSUE THREAD

**Issue by tomolse** [structurizr/onpremises#21]
I'm running the onprem version at work.
Everything was working fine until i updated from 2941 to 2983.

The diagrams wont load anymore. I have tried a minimal example, and from what i can find, the problem is visible when using "theme default" inside of the view block.

The following workspace is working as expected:
```
workspace Test {
    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }

    views {
        systemContext softwareSystem "SystemContext" {
            include *
            autoLayout lr
        }
    }

}
```

but adding theme default like the workspace under is not drawing diagrams.
```
workspace Test {
    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }

    views {
        theme default
        systemContext softwareSystem "SystemContext" {
            include *
            autoLayout lr
        }
    }

}
```

**Comment by simonbrowndotje** [comment]
Difficult to say without further information about your on-premises installation (.war file vs Docker, graphviz installed locally, etc), but I suspect it's something related to automatic layout and Internet-hosted themes (see 9.0.4 at https://structurizr.com/share/18571/documentation#faq).

It works on my on-premises installation though.

**Comment by tomolse** [comment]
I'm running it with the docker image in an internal kubernetes cluster.
It works fine if i roll back to structurizr/onpremises:2941

**Comment by tomolse** [comment]
You are correct. The problem was with the internet hosted theme file, but i was able to solve it.
