### ISSUE TITLE
Graphviz always enabled

### ISSUE THREAD

**Issue by tomolse** [structurizr/onpremises#22]
While looking at the code i found that graphviz is always enabled:
https://github.com/structurizr/onpremises/blob/main/src/main/java/com/structurizr/onpremises/util/Configuration.java#L44

Is this by design? In that case the documentation should be updated.

**Comment by simonbrowndotje** [comment]
> Is this by design?

Yes, if the on-premises installation can find `dot`, it marks Graphviz as being enabled automatically.

> In that case the documentation should be updated.

Yes, the on-premises installation switched to being the open source version ~1 week ago, and there's a batch of documentation updates coming to reflect some changes.

**Comment by tomolse** [comment]
Thank you for the quick reply 👍
