### ISSUE TITLE
"Publish all diagrams" button not working

### ISSUE THREAD

**Issue by sschutten** [structurizr/onpremises#23]
Starting with tag [#2951](https://hub.docker.com/layers/structurizr/onpremises/2951/images/sha256-32593b8c035e7d18eb9625e03762609922a020061a66ad566a2b368ef462df7f?context=explore) of the on-premises Docker image the ~~export diagrams button~~ `Publish all diagrams` button doesn't work. The following error is shown in the console of the debugging tools when the button is clicked:

```
Uncaught TypeError: structurizr.diagram.exportDiagramsToPNG is not a function
    at publishAllViews (diagram-editor:1562:37)
    at HTMLButtonElement.onclick (diagram-editor:1219:129)
```

I've verified that the button still works on the [#2950](https://hub.docker.com/layers/structurizr/onpremises/2950/images/sha256-2ef291b45563dfb940af93ecc1ca8aacdef0c9bb52781604ed6050d8f12af76b?context=explore) tag of the Docker image. Something in between these versions broke the functionality.

**Comment by sschutten** [comment]
Ah, I wasn't aware of that. We're using it to embed the diagrams in our DevOps wiki. Unfortunately it doesn't allow us to embed using an iframe, so we're stuck at embedding the PNGs. Is there some other way we're not aware of?

**Comment by simonbrowndotje** [comment]
Most of this functionality was still in the on-premises codebase, it just needed a few additions to reflect how the open source diagram viewer works differently than before. The "Publish all views" button should be back in build 2996+.
