### ISSUE TITLE
Missing /preview route

### ISSUE THREAD

**Issue by cmonty** [structurizr/onpremises#24]
When using a Docker image later than 2950, the `/preview` route no longer exists. 

For example, using 2951:

```
[WARN ] 2023-02-28 23:26:56.672 [http-nio-8080-exec-1] PageNotFound - No mapping for POST /preview
[WARN ] 2023-02-28 23:26:56.684 [http-nio-8080-exec-1] DefaultHandlerExceptionResolver - Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]
```

I suspected an issue with `dslEditor`, but even toggling that property to `true` results in the same output.

**Comment by simonbrowndotje** [comment]
This was removed in the open source version (2951+) ... I'd recommend using Structurizr Lite instead, as it will give a far better previewing experience (autolayout diagrams, manual layout diagrams, docs, decisions), particularly with [auto-refresh](https://structurizr.com/share/76352/documentation#auto-refresh) enabled.

I assume you're using VS Code ... if so, just start Lite up and point it to the same folder, then open http://localhost:8080 in your web browser.

**Comment by cmonty** [comment]
Thanks, we will give Lite a shot.
