### ISSUE TITLE
SAML SSO error after hours of usage

### ISSUE THREAD

**Issue by sschutten** [structurizr/onpremises#30]
We're using Structurizr on-premises with SAML SSO authentication using Azure AD. After hours of usage, when a user returns to Structurizr and tries to sign back in they are redirected to `/saml/SSO' and see a message `Error, Sorry, something went wrong.`. No matter what we try to do, the user won't be able to sign back in _with that browser_. We've tried clearing all application data, restarting the browser or restarting the Structurizr container.

What works is opening an in-private window and sign back in. Most of the time the next day it suddenly works again.

I've checked the logs on disk and the only logs I find are these:
```
[ERROR] 2023-03-15 14:55:23.725 [http-nio-8080-exec-7] Http500Controller - null
[ERROR] 2023-03-15 14:55:31.897 [http-nio-8080-exec-8] Http500Controller - null
[ERROR] 2023-03-15 14:55:52.211 [http-nio-8080-exec-6] Http500Controller - null
```

Checking the network activity when clicking on the sign-in button I see a successful request is made to ttps://login.microsoftonline.com/<our-tenant-id>/saml2.

Any help to further investigate this issue is welcome. It's not blocking since we can still use Structurizr in an in-private window and the next day it will resolve itself. Is there a way to turn on more verbose logging? Are sessions stored on disk and is there a way I can clear them?

**Comment by simonbrowndotje** [comment]
Perhaps this can help -> https://structurizr.com/share/18571/documentation#azure-active-directory

**Comment by sschutten** [comment]
Oh wow, I feel stupid for not have seen this in the docs nor in the issue tracker. Thanks, this sounds exactly like what I'm looking for! And thanks again for all your hard work and quick response time! Very much appreciated.
