### ISSUE TITLE
Method not supported when SAML auth is configured

### ISSUE THREAD

**Issue by karolgurecki** [structurizr/onpremises#35]
### Description

I am trying to configure Structurizer On-Premise with Azure AD SAML Authentication, but when Azure is redirecting to the application it returns 405. 
I am using latest docker build (3038).

### Steps to reproduce

Configure  SAMl Single Sing-on in Azure AD as described here https://structurizr.com/share/18571/documentation#saml-20

### Screenshot

Azure AD 
![image](https://user-images.githubusercontent.com/2675622/227767115-e4f519b2-f464-43dd-8799-0637b748507d.png)
Structurizer configuration
![image](https://user-images.githubusercontent.com/2675622/227767123-8c9fe1fc-d887-44ba-a566-493a52d3a47e.png)
Redirect result
![image](https://user-images.githubusercontent.com/2675622/227767129-7e219cff-ef5d-400b-a035-a29f6c7d6d5f.png)

### Severity

Minor

### Priority

Medium

### Resolution

I have no budget, please fix this for free

**Comment by josdeweger** [comment]
we are running into the same issue. Our configuration looks pretty similar to the OP's, we are also getting a 405 Method not allowed on the `/saml/sso` endpoint. In the logs we see the following error:
```
DefaultHandlerExceptionResolver - Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
```

but for completeness sake:
- our Structurizr app is running in an Azure Appservice
- version 3040
- we created an AAD Enterprise Application with return url `{my-app-name}/saml/sso` (where {my-app-name} is a placeholder for our real app name of course)
- added the `structurizr.properties` and `saml-idp-metadata.xml` files

`structurizr.properties`:
```
structurizr.authentication=saml
structurizr.url=https://{my-app-name}.azurewebsites.net
structurizr.saml.entityId={client id of the AAD Enterprise Application}
```

**Comment by edgrip** [comment]
Your case may have been already solved by issue #8.

You have to adjust structurizr.saml.maxAuthenticationAge property to higher (90 days ?) than the default value (2 hours): https://structurizr.com/share/18571/documentation#max-authentication-age

**Comment by HugKL** [comment]
Same problem wit keycloak here. Already tried to change the max-authentication-age to 8h, 24h, and 90 days, and didn't worked.

**Comment by samm-git** [comment]
Same on my side, KC+structurizr

**Comment by simonbrowndotje** [comment]
Somebody on the Slack group (onpremises channel) has mentioned that the instructions for Keycloak are out of date, and posted an updated screenshot. You may want to jump on there and take a look.

![image](https://github.com/structurizr/onpremises/assets/1009874/9a522d0d-9fb6-469a-89f5-e7c3453537cc)

Alternatively, you may want to try forcing authentication -> https://structurizr.com/share/18571/documentation#force-authentication (although this seems to be related to issues with Azure AD).

**Comment by samm-git** [comment]
Thank you for the screenshot, i fixed it now :)

Issue (for me) was that i disabled "sign document" function. Just in case if anyone need, sending my KC screenshot of the working configuration:
<img width="845" alt="Screenshot 2023-06-15 at 18 39 54" src="https://github.com/structurizr/onpremises/assets/1388875/928c4909-11f6-4c8b-aab7-8fa91ebda874">
<img width="827" alt="Screenshot 2023-06-15 at 18 40 10" src="https://github.com/structurizr/onpremises/assets/1388875/8c6c1e73-48c6-4ded-8383-6441e5d5b1bc">
<img width="859" alt="Screenshot 2023-06-15 at 18 40 30" src="https://github.com/structurizr/onpremises/assets/1388875/4d492100-2dc1-40b9-a959-76cbae6094a7">

**Comment by simonbrowndotje** [comment]
That's great, thanks. Would you consider sending a PR for the docs please?

https://github.com/structurizr/onpremises/blob/main/docs/docs/04-authentication.md#keycloak

**Comment by samm-git** [comment]
Done, https://github.com/structurizr/onpremises/pull/47

**Comment by albertdabrowski** [comment]
Have similar problem when integrating with Okta. I receive on server logs 
`DefaultHandlerExceptionResolver - Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]`.
This is on the returning from already authenticated user on <url>/saml/SSO

Did anyone resolved that problem? why structurizr is not accepting POST on that url.

**Comment by samm-git** [comment]
In my case it was disabled signing on the request, please check your settings.

**Comment by albertdabrowski** [comment]
> In my case it was disabled signing on the request, please check your settings

Thanks for info. I checked and `SAML Signed Request` is disabled. Anyway guys who managed OKTA said they cannot enable it, possibly there is a need for cert?
![image](https://github.com/structurizr/onpremises/assets/7994493/93fa2116-6d34-43a3-b3f1-0891d7188973)
What cert then is required? or maybe there is possibility to disable on structurizr this signing?

**Comment by albertdabrowski** [comment]
Thanks @samm-git that was also a problem on my side. Once I enabled SAML signed request then it started to work. BTW, to do that I had to export cert from jks existing on repo for structurizr onprem and upload it to Okta so then it was possible to enable it.

**Comment by glauberrs** [comment]
Hi people, i face the same problem with Azure AD and I resolved creating group claim on Enterprise Application:

<img width="868" alt="image" src="https://github.com/structurizr/onpremises/assets/12559183/d7d2be09-b394-4ca0-b1b2-76322dafca8d">

**Comment by simonbrowndotje** [comment]
Closing since the OP hasn't responded, so I'm assuming this is resolved ... please open new issues/discussions as needed.
