### ISSUE TITLE
onpremise:latest does not fully conform to SSL in `structurizr.url`

### ISSUE THREAD

**Issue by cowboygneox** [structurizr/onpremises#4]
When using a config:

```
structurizr.url=https://domain.com
```

Structurizer _mostly_ works. However, when trying to login, it's 302'ing to an `http` URL.

I am putting my API gateway in front of Structurizr to repair these broken redirects, but this appears to be a bug where the onpremise software doesn't fully respect `structurizr.url`.

**Comment by simonbrowndotje** [comment]
I'm unable to reproduce this I'm afraid. Do you have any more details?

**Comment by cowboygneox** [comment]
Let's see...

I'm running this in EKS. I configured it with a `LoadBalancer` that was an NLB that terminates SSL under the hood.

It specifically happened when I would go from the dashboard to signin. When the 302 redirect would pop-in, it would redirect to an `http` address even though everything else was using `https` just fine.

**Comment by cowboygneox** [comment]
And now with my Kong gateway in front of it, I'm getting a 405 when trying to `POST` to `/login`. The logs aren't helping me either.

**Comment by cowboygneox** [comment]
Ah, the 405 was a high-availability issue; I had two pods configured pointing to S3, but apparently there's some other shared state that I don't know how to configure. I can make a different issue for that.
