### ISSUE TITLE
Make application read properties also from environment variables

### ISSUE THREAD

**Issue by amalic** [structurizr/onpremises#40]
### Description

Properties file is required to have e.g. DSL editor enabled. It would be great if the application could check first if a properties file is present, and if not present check if properties have been provided through the environment. This would help with running it on a fresh Kubernetes using persistent volumes.

### Priority

Medium

### Resolution

I have no budget, please add this feature for free

**Comment by ravensorb** [comment]
Maybe provide a default version of the structrizr.properties file that uses environment variables for each of the settings?

**Comment by simonbrowndotje** [comment]
Closing as not planned.
