### ISSUE TITLE
Helm based installation for the k8s

### ISSUE THREAD

**Issue by samm-git** [structurizr/onpremises#46]
### Description

Dear authors, 

while exploring `structurizr` I created helm (based on initial effort found in https://github.com/virtualroot/charts/commits/main/charts/structurizr).  My changes have been to add PVC support, custom mounts, and the ability to override the property file. 

I would be glad to contribute all my changes to the upstream, to have a straightforward way to install structurizr in Kubernetes. My version of the helm is available at https://github.com/samm-git/structurizr-chart, please let me know if you are willing to accept it, I can do a PR, or you can import it to the new repo.

Thank you

### Priority

Low

### Resolution

I'm willing to add this feature myself and raise a PR

**Comment by khanh96le** [comment]
Hi @simonbrowndotje @samm-git, do you have any plan to process this enhancement?
This feature would be very helpful.

**Comment by simonbrowndotje** [comment]
Thanks @samm-git. I don't think this is something that needs to be contained within this repo (I don't know Helm myself, so wouldn't be able to support it), but I can certainly add a link back to your repo from the docs.

**Comment by simonbrowndotje** [comment]
Closing as stale.
