### ISSUE TITLE
Structurizr with Keycloak : Request method 'POST' not supported

### ISSUE THREAD

**Issue by armanddebesse** [structurizr/onpremises#59]
## Server description ##
I have a structurizr and keycloak containairs behind a reverse proxy nginx.  
I want to authenticate with SAML.  

## Problem description ##
When I click on "Sign In" button in structurizr web UI, I got successfully redirected to keycloak login page.  
After I validate my credentials, I got successfullt redirected to https://structurizr.mydomain.fr/saml/SSO.  
At this moment I got a blank page and I'm stuck on https://structurizr.mydomain.fr/saml/SSO, but I shloud be redirected on dashboard as an authenticated user.  
**I have a 405 error in my console**  
![image](https://github.com/structurizr/onpremises/assets/73818074/5c277c13-a9bc-4797-a1ae-3c0b95f637bb)

And I have this error in structurizr logs : `structurizr-structurizr-1  | [WARN ] 2023-08-26 11:32:24.532 [http-nio-8080-exec-3] DefaultHandlerExceptionResolver - Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]`

### Steps to reproduce

1. Configure keycloak container (v.22.0) following the official documentation https://structurizr.com/public/18571/documentation#overview
2. Configure structurizr onpremises (v.3130) container for saml following the official documentation https://structurizr.com/public/18571/documentation#overview
3. Create a keycloak user and try to connect to structurizr with him.

### Severity

Minor

### Priority

Low

### Resolution

I have no budget, please fix this for free

**Comment by simonbrowndotje** [comment]
I'd recommend looking at [Troubleshooting - SAML integration](https://structurizr.com/public/18571/documentation#saml-integration) (i.e. debugging the SAML handshake and enabling debug in the logs to see any error messages). There's also some discussion of Keycloak in the [Slack group](https://join.slack.com/t/structurizr/shared_invite/enQtMzkyMjY1NzMwNTkzLTcyOGI1MTZmNDQwMDQ5YmZlMThiYmU1ZTM2ZWZiMzYwMjVhNmM0OWIwNjFlZTM1YmY3YzU0ZDY2MTA1YTk5Mjg) onpremises channel.

**Comment by armanddebesse** [comment]
It helped thanks !  
I had a problem with my headers behind my reverse proxy. I fixed it.  
After I needed to update structurizr.properties like specified at https://structurizr.com/public/18571/documentation#saml-integration with : `structurizr.saml.forceAuthentication=true` and increase value of  `structurizr.saml.maxAuthenticationAge` .  

Thanks a lot, I will continue to enjoy diagramming with structurizr !

**Comment by khanh96le** [comment]
Save the answer in Slack for reference, as messages can be deleted.

![Screenshot 2023-09-19 at 10 43 26](https://github.com/structurizr/onpremises/assets/19431276/8bf91ad4-bc05-412c-922b-0fe3373af4b4)
