### ISSUE TITLE
Content Security Policy / SAML Keycloak

### ISSUE THREAD

**Issue by cyberjeff-u8t** [structurizr/onpremises#86]
### Description

SAML authentication with keycloak was working with build 3114 but after upgrade to latest version,
I can see following error in browser console after clicking on 'sign-in' button:

Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-MDNkMzRiNzctNTQyMS00MjJjLTlkN2YtMmI1NDk4YjM1ZTlm'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

### Steps to reproduce

1. configure saml/keycloak 
2. open structurizr onpremise home page
3. click sign-in button

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

**Comment by borismus-hawk** [comment]
Hello @simonbrowndotje ,

any update on this bug? I have the same issue with keycloak integration.

Thanks in advance

**Comment by simonbrowndotje** [comment]
We don't have any paying customers who use Keycloak, so it's not very high on the todo list I'm afraid ... the code is open source, so I was hoping somebody in the community would resolve this.

Just FYI though, the on-premises installation is being upgraded to Spring 6/Tomcat 10 ([branch](https://github.com/structurizr/onpremises/tree/jakarta-ee)), which completely changes the SAML integration ... so it might not be worth anybody resolving this now.

**Comment by borismus-hawk** [comment]
@simonbrowndotje , Many thanks Simon! I think I can wait for it. Anyway, thanks for the great project!

**Comment by simonbrowndotje** [comment]
If you'd like to try it, a preview of the new Spring 6/Tomcat 10 build is available via Docker at the `structurizr/onpremises:preview` image. The SAML configuration is different; see https://docs.structurizr.com/onpremises/authentication/aml#preview-build-spring-6tomcat-10 for some basic instructions.

**Comment by borismus-hawk** [comment]
@simonbrowndotje

Thanks a lot Simon! appreciate this!

Unfortunately, now it gives me another error when redirects to /saml2/authenticate/default:
![image](https://github.com/structurizr/onpremises/assets/53830793/b945a6cc-3047-486d-9644-ff3857b1c411)

Logs:
```
[DEBUG] 2023-12-21 16:33:03.848 [http-nio-8080-exec-4] FilterChainProxy - Securing GET /dashboard
[DEBUG] 2023-12-21 16:33:03.850 [http-nio-8080-exec-4] FilterChainProxy - Secured GET /dashboard
[DEBUG] 2023-12-21 16:33:03.856 [http-nio-8080-exec-4] AnonymousAuthenticationFilter - Set SecurityContextHolder to anonymous SecurityContext
[DEBUG] 2023-12-21 16:33:03.869 [http-nio-8080-exec-4] MethodSecurityInterceptor - Failed to authorize ReflectiveMethodInvocation: public java.lang.String com.structurizr.onpremises.web.home.HomePageController.showAuthenticatedDashboard(java.lang.String,int,int,org.springframework.ui.ModelMap); target is of class [com.structurizr.onpremises.web.home.HomePageController] with attributes [[authorize: 'isAuthenticated()', filter: 'null', filterTarget: 'null']]
[DEBUG] 2023-12-21 16:33:03.876 [http-nio-8080-exec-4] HttpSessionRequestCache - Saved request https://structurizr.mydomain.com/dashboard?continue to session
[DEBUG] 2023-12-21 16:33:03.877 [http-nio-8080-exec-4] DelegatingAuthenticationEntryPoint - Trying to match using And [Not [RequestHeaderRequestMatcher [expectedHeaderName=X-Requested-With, expectedHeaderValue=XMLHttpRequest]], Not [And [Or [Ant [pattern='/login'], Ant [pattern='/favicon.ico']], And [Not [RequestHeaderRequestMatcher [expectedHeaderName=X-Requested-With, expectedHeaderValue=XMLHttpRequest]], MediaTypeRequestMatcher [contentNegotiationStrategy=org.springframework.web.accept.HeaderContentNegotiationStrategy@67f9f5b3, matchingMediaTypes=[application/xhtml+xml, image/*, text/html, text/plain], useEquals=false, ignoredMediaTypes=[*/*]]]]]]
[DEBUG] 2023-12-21 16:33:03.884 [http-nio-8080-exec-4] DelegatingAuthenticationEntryPoint - Match found! Executing org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint@2377b5b
[DEBUG] 2023-12-21 16:33:03.886 [http-nio-8080-exec-4] DefaultRedirectStrategy - Redirecting to https://structurizr.mydomain.com/saml2/authenticate/default
```
structurizr.properties:
```
structurizr.feature.ui.dslEditor=true
structurizr.url=https://structurizr.mydomain.com
structurizr.admin=structurizr
structurizr.data=aws-s3
structurizr.authentication=saml
structurizr.saml.metadata=https://keycloak.mydomain.com/auth/realms/services/protocol/saml/descriptor
structurizr.saml.entityId=structurizr
structurizr.saml.signing.certificate=mydomain.com.cer
structirizr.saml.signing.privateKey=mydomain.com.key
aws-s3.accessKeyId=***********
aws-s3.secretAccessKey=*****************
aws-s3.bucketName=structurizr
aws-s3.endpoint=https://blobstorage.mydomain.com:9000
aws-s3.pathStyleAccess=true
```

Everything is configured according to the instruction. Although, maybe I've missed something...

**Comment by maycson-ciandt** [comment]
I have the same problem using Okta.

```javascript
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-MDNkMzRiNzctNTQyMS00MjJjLTlkN2YtMmI1NDk4YjM1ZTlm'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

**Comment by simonbrowndotje** [comment]
> I have the same problem using Okta.

The current Spring 5/Tomcat 9 build will be superseded in a week or so - I'd recommend trying the new version (`structurizr/onpremises:preview`) with Okta ... there's an example SAML configuration at https://docs.structurizr.com/onpremises/authentication/saml#preview-build-spring-6tomcat-10 (this is taken from the Spring Security samples):

```
# Okta (testuser2@spring.security.saml/12345678)
structurizr.authentication=saml
structurizr.saml.registrationId=one
structurizr.saml.metadata=https://dev-05937739.okta.com/app/exk46xofd8NZvFCpS5d7/sso/saml/metadata
structurizr.saml.attribute.username=email
```

**Comment by simonbrowndotje** [comment]
> Everything is configured according to the instruction. Although, maybe I've missed something...

You will just need to debug the SAML handshakes, etc I'm afraid; see https://docs.structurizr.com/onpremises/authentication/saml#troubleshooting for some pointers.

**Comment by simonbrowndotje** [comment]
The Jakarta EE/Spring 6 version of the on-premises installation has now been released, which provides a new SAML integration mechanism ... closing as stale.
